[package]
name = "evo-kernel-agent-skill-manage"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "evo-agent-skill-manage"
path = "src/main.rs"

[dependencies]
evo-agent-sdk = { path = "../evo-agents/evo-agent-sdk" }
tokio         = { version = "1", features = ["full"] }
anyhow        = "1.0"
